services:
  ui:
    image: somkiat/demo-react:1.0.0
    build:
      context: ./demo-react
      dockerfile: Dockerfile
    ports:
      - "8001:80"
  
  ui_test:
    build: ./ui-test
    tty: true
    volumes:
      - ./ui-testing-playwright-report:/app/report
  
  api_test:
    build: ./api-test
    tty: true
    volumes:
      - ./api-testing-report:/etc/newman/newman