services:
  ui:
    image: somkiat/demo-react:1.0.0
    build:
      context: ./demo-react
      dockerfile: Dockerfile
    ports:
      - "8001:80"
  
  ui_test:
    build: ./ui-test
    tty: true
    volumes:
      - ./ui-testing-playwright-report:/app/report
  
  api_test:
    build: ./api-test
    tty: true
    volumes:
      - ./api-testing-report:/etc/newman/newman

  sonarscanner_react:
    image: sonarsource/sonar-scanner-cli
    environment:
      - SONAR_HOST_URL=http://174.138.24.226:9000
      - SONAR_TOKEN=sqa_9d166946ac924b1b0852c8c3cac86d7ab0cb416c
      - SONAR_LOGIN=admin
      - SONAR_PASSWORD=xitgmLwmp
      - SONAR_PROJECT_BASE_DIR=/app
    volumes:
      - ./demo-react:/app
  
  mock_api:
    build: 
      context: ./mock-api
      dockerfile: Dockerfile
    tty: true
    ports:
      - "9999:8882"

  mock_db:
    build: 
      context: ./mock-db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo